/* AUTO-GENERATED by make/gen_build_info.py on 2026-09-06 02:00:16.
 * Do NOT edit by hand - this file is rewritten on every build. */
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 0
#define FW_VERSION_PATCH 0

#define FW_VERSION_STR "1.0xa"

#define BUILD_DATE "2026-09-06"   /* YYYY-MM-DD */
#define BUILD_TIME "02:00:16"   /* HH:MM:SS  */

#endif /* BUILD_INFO_H */
