/* AUTO-GENERATED by make/gen_build_info.py on 2026-07-12 01:55:00.
 * Do NOT edit by hand - this file is rewritten on every build. */
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define FW_VERSION_MAJOR 0
#define FW_VERSION_MINOR 9
#define FW_VERSION_PATCH 0

#define BUILD_DATE "2026-07-12"   /* YYYY-MM-DD */
#define BUILD_TIME "01:55:00"   /* HH:MM:SS  */

#endif /* BUILD_INFO_H */
