#!/usr/bin/env python3
"""Generate src/build_info.h with the current build date/time + version.

Invoked from the makefile `pre-build` step on every build, so the build
timestamp always reflects when the firmware was actually compiled.

Usage:  python gen_build_info.py <output_header_path>
"""
import sys, os, datetime

FW_MAJOR = 0
FW_MINOR = 9
FW_PATCH = 0

def main():
    if len(sys.argv) < 2:
        print("gen_build_info.py: missing output path", file=sys.stderr)
        sys.exit(1)
    out = sys.argv[1]
    now = datetime.datetime.now()
    date_str = now.strftime("%Y-%m-%d")   # e.g. 2026-06-21
    time_str = now.strftime("%H:%M:%S")   # e.g. 13:45:07

    content = """/* AUTO-GENERATED by make/gen_build_info.py on {date} {time}.
 * Do NOT edit by hand - this file is rewritten on every build. */
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define FW_VERSION_MAJOR {maj}
#define FW_VERSION_MINOR {min}
#define FW_VERSION_PATCH {pat}

#define BUILD_DATE "{date}"   /* YYYY-MM-DD */
#define BUILD_TIME "{time}"   /* HH:MM:SS  */

#endif /* BUILD_INFO_H */
""".format(maj=FW_MAJOR, min=FW_MINOR, pat=FW_PATCH, date=date_str, time=time_str)

    # Only rewrite if the content changed, to avoid touching the timestamp
    # unnecessarily (and re-triggering rebuilds of dependents in incremental
    # builds).  On a clean build the file always gets created.
    write = True
    if os.path.exists(out):
        try:
            with open(out, "r", encoding="utf-8") as f:
                if f.read() == content:
                    write = False
        except Exception:
            write = True
    if write:
        try:
            os.makedirs(os.path.dirname(out), exist_ok=True)
        except Exception:
            pass
        with open(out, "w", encoding="utf-8") as f:
            f.write(content)

if __name__ == "__main__":
    main()
